spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: huanghongtao520
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC&useSSL=true&useUnicode=true&characterEncoding=utf-8
mybatis:
  type-aliases-package: com.example.springboot04.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml